Change deployment to kubernetes deployment + Add Github Cleaner

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  build:
+  build: # TODO: REMOVE THIS STEP AFTER AMT HAS BEEN CHANGED TO USE THE API
     runs-on: ubuntu-latest
 
     steps:
@@ -33,28 +33,27 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Get GHCR package hash
         id: get_package_hash
         run: |
-          container_id=$(gh api --paginate -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/MinBZK/packages/container/amt/versions | jq -r '.[] | select(.metadata.container.tags | contains(["${{ inputs.image_tag }}"])) | .name')
-          echo "container_id=$container_id" >> "$GITHUB_OUTPUT"
+            container_id=$(gh api --paginate -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/MinBZK/packages/container/instrument-registry/versions | jq -r '.[] | select(.metadata.container.tags | contains(["main"])) | .name')
+            echo "container_id=$container_id" >> "$GITHUB_OUTPUT"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: check correct name
         run: |
-          if [ -z "${{steps.get_package_hash.outputs.container_id}}" ]; then
-            echo "Variable is empty. Failing the workflow."
-            exit 1
-          fi
+            if [ -z "${{steps.get_package_hash.outputs.container_id}}" ]; then
+              echo "Variable is empty. Failing the workflow."
+              exit 1
+            fi
 
       - uses: actions/checkout@v4
         with:
-          repository: "minbzk/ai-validation-infra"
+          repository: 'minbzk/ai-validation-infra'
           ref: main
           token: ${{ secrets.GH_PAT }}
 
@@ -63,18 +62,19 @@ jobs:
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
+
       - name: Make changes to the file
         run: |
-          sed -i 's/newTag: .*$/newTag: ${{inputs.image_tag  }}@${{ steps.get_package_hash.outputs.container_id }}/g' apps/amt/overlays/${{ inputs.environment }}/kustomization.yaml
-          sed -i 's|minbzk.github.io/version: .*$|minbzk.github.io/version: ${{ inputs.image_tag }}|g' apps/amt/overlays/${{ inputs.environment }}/kustomization.yaml
-          git add apps/amt/overlays/${{ inputs.environment }}/kustomization.yaml
+          sed -i 's/newTag: .*$/newTag: main@${{ steps.get_package_hash.outputs.container_id }}/g' apps/instrument-registry/sandbox/kustomization.yaml
+          sed -i 's|minbzk.github.io/version: .*$|minbzk.github.io/version: main|g' apps/instrument-registry/sandbox/kustomization.yaml
+          git add apps/instrument-registry/sandbox/kustomization.yaml
 
       - name: show changes
         run: git diff --staged
 
       - name: push changes
         run: |
-          git commit -m "Update amt overlay ${{ inputs.environment }} tag ${{ steps.get_package_hash.outputs.container_id }}"
+          git commit -m "Update instrument-registry sandbox tag ${{ steps.get_package_hash.outputs.container_id }}"
           git push --force-with-lease
         env:
           GITHUB_TOKEN: ${{ secrets.GH_PAT }}
